#!/usr/bin/env bash
# Cloud Agent start: Cursor Secrets → .env.local（スクリプト互換用）
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env.local"

# .env.example と同じキー。設定されているものだけ書き出す。
KEYS=(
  NEXT_PUBLIC_SUPABASE_URL
  NEXT_PUBLIC_SUPABASE_ANON_KEY
  SUPABASE_SERVICE_ROLE_KEY
  GOOGLE_SERVICE_ACCOUNT_EMAIL
  GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY
  GOOGLE_CALENDAR_ID
  GOOGLE_BOOKING_FORM_SPREADSHEET_ID
  GOOGLE_REQUEST_FORM_SPREADSHEET_ID
  GOOGLE_BOOKING_FORM_SHEET_NAME
  GOOGLE_REQUEST_FORM_SHEET_NAME
  CRON_SECRET
  FORM_SYNC_DISABLED
  MAIL_PROVIDER
  FACILITY_NAME
  MAIL_FROM
  MAIL_FROM_ADDRESS
  MAIL_FROM_NAME
  MAIL_REPLY_TO
  SMTP_HOST
  SMTP_PORT
  SMTP_SECURE
  SMTP_USER
  SMTP_PASS
  RESEND_API_KEY
  STUDIO_BOOKING_FORM_URL
  NEXT_PUBLIC_APP_URL
  SKIP_AUTH
)

written=0
{
  echo "# Generated by scripts/cloud-write-env-local.sh — do not commit"
  for key in "${KEYS[@]}"; do
    val="${!key:-}"
    if [[ -n "$val" ]]; then
      # 値に改行・引用符が含まれる場合はダブルクォートでエスケープ
      escaped="${val//\\/\\\\}"
      escaped="${escaped//\"/\\\"}"
      escaped="${escaped//$'\n'/\\n}"
      printf '%s="%s"\n' "$key" "$escaped"
      written=$((written + 1))
    fi
  done
} > "$ENV_FILE"

if [[ "$written" -gt 0 ]]; then
  echo "cloud-write-env-local: wrote $written vars to .env.local"
else
  rm -f "$ENV_FILE"
  echo "cloud-write-env-local: no secrets in environment (skipped .env.local)"
fi
